# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - configserverv1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://rnbootcamp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b9c8d4b4e55a4c2ca76b1cf035debd59 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1c821ff7724a4e22842246b561cd49a2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rnbootcamp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9c8d4b4e55a4c2ca76b1cf035debd59 }}/config-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'configserverv1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4854c1f3c5e74ee2b7e15d940975ea5f }}
        images: 'rnbootcamp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9c8d4b4e55a4c2ca76b1cf035debd59 }}/config-server:${{ github.sha }}'